### PR TITLE
Switch to GitHub Actions CI.

### PR DESCRIPTION
**Pull request by XhmikosR**
Notes:

1. you won't see the Actions firing up in the PR due to security reasons. After the merge, they should work normally (assuming they are not disabled in the repo settings). Preview: <https://github.com/XhmikosR/picomatch/runs/298838786>
2. Personally, I wouldn't test non-LTS old versions like 11; it's -3 jobs
3. Currently there's no caching on GitHub Actions CI, but this feature should be implemented pretty soon

If you decide to merge this, you should remove any Travis CI hooks/apps/integrations from the repo settings.

PS. there's seems to be a temporary slowness at the time of writing.

Either way, it's your call. :)

### CODE REVIEW

**Comment by doowb** [comment]
I like this, but I think keeping the Travis CI integration for a little bit would be good, at least to see if there are any differences, especially on Windows.

**Comment by XhmikosR** [comment]
Until a few days ago, GH Actions on Windows was using the native cmd. Now I notice it defaults to PowerShell. That being said, it seems tests work fine either way.

But yeah, feel free to wait a bit :)

**Comment by XhmikosR** [comment]
I think this is ready @doowb @jonschlinkert.

Do note that I don't run coveralls for all OS'es and Node.js versions, only on Ubuntu and Node.js 12.x. Not sure if it matters.

Also, should I remove Node.js 11??

Preview: <https://github.com/XhmikosR/picomatch/runs/300623029>

**Comment by XhmikosR** [comment]
Oh, forgot to mention that there's an issue https://github.com/coverallsapp/github-action/issues/5. I've tried contacting them and GitHub also, but I couldn't get a response from them.

**Comment by XhmikosR** [comment]
The issue with the coveralls action seems to be fixed. So the only thing left is if we are going to keep Node.js 11 or not.

**Comment by doowb** [comment]
I say remove Node.js 11 since 13 is available. For the odd versions, I usually only test against the latest.

**Comment by XhmikosR** [comment]
Yup, totally agree. If for any reason you need to run Coveralls on all Node.js versions and OS'es, just remove the `if` line later.

**Comment by XhmikosR** [comment]
BTW I didn't add a coverage badge in README.md, but feel free to add one.

**Comment by doowb** [comment]
Thanks for this PR! I like that in the commit "checks" status I can see each os/version combo separately.

I like the `if` line in there ;) I didn't know you could do that.

**Comment by XhmikosR** [comment]
Oh, also we could probably split the actions and like run Lint only on one OS and Node.js version. But you get the idea :)

**Pull request merged**
