### PR TITLE
Remove `process` and `path` dependencies, document `windows` option

### PR DESCRIPTION
**Pull request by silverwind**
To make this module usable in other environments besides Node.js, it must not depend on node builtin modules. This PR does:

1. `process.platform` is replaced via the existing but undocumented `windows` option which is now documented.
2. `path.basename` is replaced by a simple regex replacement.

This is a breaking change for all users who are passing backslashes to this module and they need to pass `process.platform === 'win32'` as the `windows` option to attain previous behavior.

One additional benefit of this change is that the tests no longer need to monkey-patch the `path` module.

Fixes: https://github.com/micromatch/picomatch/issues/61
Fixes: https://github.com/micromatch/picomatch/issues/64
Fixes: https://github.com/micromatch/picomatch/issues/68

### CODE REVIEW

**Comment by jonschlinkert** [comment]
@silverwind thank you so much for this PR. I'm really sorry for the very late reply, I took some time away from GitHub for a few months, but I'll be much more active going forward. 

I'm getting caught up, so I'll be reviewing this PR soon and hopefully get this merged.

**Comment by YeomansIII** [comment]
Is this PR still under consideration? Or is there another way to get around these dependencies (specifically `process`) in the browser?

**Comment by acao** [comment]
This PR works 💯! This library already works in create react app/webpack, but elsewise our users had issues with `process`. Our library builds in vite now. The only thing left after this is `path.basename` it looks like?

**Comment by acao** [comment]
@silverwind would you be interested in a PR against your fantastic PR to replace `path.sep` to round it out?

**Comment by silverwind** [comment]
Yes, `path.sep` usage should be removed as well to make this module work in all environments. Default to `/` and `\\` when `windows` is passed. I will check this out later.

**Comment by acao** [comment]
Awesome! I have temporarily published this branch plus the commit to remove path.sep as `picomatch-browser` on npm for our users, with a note showing it’s temporary. It’s an experimental package that doesn’t have many downloads yet.

I wonder - does this constitute a breaking change? Where picomatch previously worked with windows by default? If so, I have an idea -

this would exhibit the previous behavior by default, using `os` module to detect whether options.windows is true or false:

```ts
import picomatch from 'picomatch'
```

Whereas this would be used for import without node dependencies, and options.windows would require manual opt in as is current behavior:

```ts
import picomatch from 'picomatch/core'
```

**Comment by silverwind** [comment]
Sounds like an idea for compatibilty. I would call it `picomatch/posix`, like [`path.posix`](https://nodejs.org/api/path.html#pathposix).

**Comment by acao** [comment]
this is what I have so far, trying to figure out how best to not break all the exports without resorting to commonjs magic. I'm sure there's something simple I'm overlooking here! tests pass, but I will need to add at least a few more to test the difference between these interfaces.

```js
'use strict';

const os = require('os');
const picomatch = require('./lib/picomatch');

const isWindows = os.platform() === 'win32';

function nodePicomatch(glob, options, returnState = false) {
  // default to os.platform()
  if (options.windows === null || options.windows === undefined) {
    options.windows = isWindows;
  }
  return picomatch(glob, options, returnState);
}

module.exports = nodePicomatch;
module.exports.makeRe = picomatch.makeRe;
module.exports.isMatch = picomatch.isMatch;
module.exports.parse = picomatch.parse;
// do we need to export these as well?
module.exports.scan = picomatch.scan;
module.exports.compileRe = picomatch.compileRe;
module.exports.constants = picomatch.constants;
```

**Comment by silverwind** [comment]
Merged the changes for `picomatch/posix` which defaults `path.sep` to `/`. Regular `picomatch` will include Windows compatibilty, meaning this change is no longer a breaking one.

**Comment by silverwind** [comment]
Seems the maintainers have no interest in removing these node dependencies, so I can recommend [minimatch](https://github.com/isaacs/minimatch) instead which while slower, has no `node` dependencies so works in all environments.

**Comment by dawidk92** [comment]
@doowb @jonschlinkert could you please take a look at this PR? Without it, we can't use picomatch in React Native.

**Comment by acao** [comment]
@silverwind `picomatch-browser` has about 113k downloads/month now 😂 🤷‍♀️ we will go live with it in a tool that has a million downloads a month soon

**Comment by jdalrymple** [comment]
Any update on this PR? Is there something that needs doing still to be accepted?

**Comment by acao** [comment]
@jonschlinkert thank you so much for merging this! i will soon deprecate `picomatch-browser` and point users back here.

**Comment by jonschlinkert** [comment]
@acao no worries, and thank you for providing an interim solution. I'm sure the community appreciates it.

**Pull request merged**
