### PR TITLE
Change mocha reporter to dot.

### PR DESCRIPTION
**Pull request by XhmikosR**
This brings test time down ~1s from ~15s on my Windows machine.

Linux might not see such a huge improvement, but it should still be faster.

### CODE REVIEW

**Comment by XhmikosR** [comment]
Some notes:

1. Travis is using bash on Windows too hence why this doesn't save anything there
2. This only happens with Windows native cmd

So, I understand if you don't accept this patch. Just be aware it's like 20x slower on Windows native cmd.

**Comment by jonschlinkert** [comment]
> This brings test time down ~1s from ~15s on my Windows machine.

Wow, something doesn't sound right there. This is what I get on Windows:

Windows native cmd

image

Windows bash

image

Windows hyper with powershell 

image

Windows ConEmu with cmder

image

On mac:

image

Hmm, what version of node.js are you running? 

Thanks for the PR. I'm not opposed to merging, but would love to figure out what's causing that slowness if possible.

**Comment by XhmikosR** [comment]
I'm using Node.js 12.13.0, but it might be Windows Defender. The above numbers were on my XPS 9570 where I haven't disabled it.

On my dev Windows VM, I get `1946 passing (3s)` for master and ` 1946 passing (1s)` for this branch.

**Comment by XhmikosR** [comment]
It seems this is faster on Travis too `2s` vs `1s`. Generally, from my experience, I've found the less we output the faster :)

**Comment by jonschlinkert** [comment]
> Generally, from my experience, I've found the less we output the faster :)

Agreed, but sometimes insight and clarity trumps speed. Regarding preferences, I don't mind using the dot reporter. Thanks for the pr!

**Pull request merged**
