### PR TITLE
Tweak nyc config and script.

### PR DESCRIPTION
**Pull request by XhmikosR**
This will conflict with #44, but I will rebase when needed.

The idea is that we reuse the same command.

BTW I was wondering, shouldn't there be a service like code-cov or something set up? With #37 we don't need to even add a devDependency; we can just use an action for this.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
> BTW I was wondering, shouldn't there be a service like code-cov or something set up?

I'd definitely be in favor of that!

**Comment by XhmikosR** [comment]
@jonschlinkert feel free to add a service then. I will change this PR tomorrow to output `lcov` too which should work out of the box with at least coveralls.

Feel free to ping me if you want me to make any coverage-related changes, like scripts, badges etc.

**Comment by jonschlinkert** [comment]
> Feel free to ping me if you want me to make any coverage-related changes, like scripts, badges etc.

I'm open to any improvements you want to make! Regarding badges specifically, I usually like keeping them to a minimum, but I don't have strong feelings about it. Just a "soft" preference.

**Comment by XhmikosR** [comment]
@jonschlinkert it depends if you want to add coveralls or a similar service to your repo :) If we merge #37 we won't even need a new devDependency.

Currently, the `cover` script does not run on CI.

**Comment by doowb** [comment]
@XhmikosR I'm going to merge in #37. From your previous comment, do you want to add a the action first? Or does the service need to be configured before adding the action?

**Comment by XhmikosR** [comment]
I'd say just add it to the repo and make sure PR comments are disabled.
Then ping me and tomorrow I will update the actions PR with coveralls
support. Or whatever service you choose.

**Comment by doowb** [comment]
Done... no rush and thanks again!

**Pull request merged**
